(() => {
  const { constants, data, dateScope, theme, utils } = window.ARA.shared;
  const detail = window.ARA.paperDetail;
  const { DEFAULT_DOMAIN_ORDER, DOMAIN_META, DEFAULT_THEME, THEMES } = constants;
  const { aggregateDailyPayloads, fetchDataJson, resolveDataBasePath } = data;
  const { buildDateScopeLabel, buildRangeScopeFromCount, clampDateToAvailable, getDateDialogScope, getScopeDates, readScopeFromDialog, syncDateDialog, updateDateTrigger } = dateScope;
  const { applyTheme, getTheme, updateThemeSelectionUI } = theme;
  const { escapeHtml, formatAffiliations, formatAuthors, formatPublished, normalizePaperId, previewText, enableDialogOutsideClose } = utils;

  let currentPapers = [];
  let currentFilteredPapers = [];
  let currentDate = "";
  let currentDateLabel = "";
  let currentDateMode = "single";
  let currentDateRange = null;
  let availableDates = [];
  let paperDetailController;

  const getCurrentScopeCacheKey = () => (currentDateMode === "range" && currentDateRange ? `${currentDateRange.start}_to_${currentDateRange.end}` : currentDate || availableDates[0] || "");
  const getKnownDomains = (papers = []) => [...DEFAULT_DOMAIN_ORDER, ...Array.from(new Set(papers.map((paper) => paper.domain || "general"))).filter((item) => !DEFAULT_DOMAIN_ORDER.includes(item)).sort()];
  const getDomainLabel = (domain) => DOMAIN_META[domain]?.label || domain;
  const currentDialogScope = () => getDateDialogScope({ currentDateMode, currentDate, currentDateRange, availableDates });
  const syncDateSelectionDialog = (scope = currentDialogScope()) => syncDateDialog({ availableDates, scope, singleFallbackDate: currentDate || availableDates[0], rangeFallbackStart: scope.start || availableDates[Math.min(availableDates.length - 1, 2)] || availableDates[0] });

  const syncDomainOptions = () => {
    const select = document.getElementById("domain-filter");
    if (!select) return;
    const currentValue = select.value || "all";
    const domains = getKnownDomains(currentPapers);
    select.innerHTML = domains.map((domain) => `<option value="${escapeHtml(domain)}">${escapeHtml(getDomainLabel(domain))}</option>`).join("");
    select.value = domains.includes(currentValue) ? currentValue : "all";
  };

  const renderStatus = () => {
    const settings = detail.utils.getLocalSettings();
    const localAiReady = detail.utils.hasLocalAiConfig();
    const modeText = settings.storageMode === "session" ? "This session" : "This device";
    const contextText = settings.researchContext ? "Configured" : "Not set";
    const themeText = THEMES[getTheme()]?.label || THEMES[DEFAULT_THEME].label;
    const aiLanguageText = detail.utils.getAiLanguageMeta(detail.utils.getPreferredAiLanguage()).label;
    const viewText = currentDateLabel ? `${currentDateLabel} · ${currentDateMode === "range" ? "Range view" : "Single day"}` : "Not loaded";
    const configText = localAiReady ? '<span class="ok">Ready</span> for local Spark / follow-up' : '<span class="warn">Not set</span> · add API in Settings';
    document.getElementById("local-status").innerHTML = `
      <div class="local-status-desktop">
        <strong>Daily report:</strong> Generated by GitHub.<br />
        <strong>Local enhancement:</strong> ${configText}<br />
        <strong>View:</strong> ${escapeHtml(viewText)}<br />
        <strong>Storage:</strong> ${escapeHtml(modeText)} · <strong>Research context:</strong> ${escapeHtml(contextText)} · <strong>Theme:</strong> ${escapeHtml(themeText)} · <strong>Detail language:</strong> ${escapeHtml(aiLanguageText)}
      </div>
      <details class="local-status-mobile">
        <summary class="local-status-mobile-summary"><span class="local-status-mobile-title">${escapeHtml(viewText)}</span><span class="local-status-mobile-hint">More</span></summary>
        <div class="local-status-mobile-pills"><span class="meta-pill meta-pill-strong">${escapeHtml(currentPapers.length ? `${currentPapers.length} papers` : "No papers")}</span><span class="meta-pill">${escapeHtml(localAiReady ? "Local ready" : "Local off")}</span><span class="meta-pill">${escapeHtml(themeText)}</span><span class="meta-pill">${escapeHtml(aiLanguageText)}</span></div>
        <div class="local-status-mobile-body"><div class="local-status-mobile-row"><strong>Daily report</strong><span>Generated by GitHub.</span></div><div class="local-status-mobile-row"><strong>Local enhancement</strong><span>${configText}</span></div><div class="local-status-mobile-row"><strong>Storage</strong><span>${escapeHtml(modeText)}</span></div><div class="local-status-mobile-row"><strong>Research context</strong><span>${escapeHtml(contextText)}</span></div></div>
      </details>
    `;
  };

  const paperCard = (paper, index) => {
    const ai = detail.utils.getAiSection(paper.ai || {}, "zh");
    const codeTag = paper.code?.has_code ? '<span class="tag">Code</span>' : "";
    const affiliationPreview = formatAffiliations(paper.affiliations || []);
    const reportMeta = currentDateMode === "range" ? `Report ${escapeHtml(paper.source_date || (paper.report_dates || [])[0] || "-")}${(paper.report_dates || []).length > 1 ? ` · ${escapeHtml(String(paper.report_dates.length))} picks` : ""}` : escapeHtml(formatPublished(paper.published));
    return `
      <article class="paper-card panel" data-paper-id="${normalizePaperId(paper.id)}">
        <div class="paper-card-head"><div class="paper-card-order">#${index + 1}</div><div class="paper-card-tags">${codeTag}<span class="tag">${escapeHtml(paper.domain || "general")}</span></div></div>
        <h3 class="paper-card-title">${escapeHtml(paper.title)}</h3>
        <p class="paper-card-authors">${escapeHtml(formatAuthors(paper.authors || []))}</p>
        ${affiliationPreview ? `<p class="paper-card-affiliations">${escapeHtml(affiliationPreview)}</p>` : ""}
        <div class="paper-card-meta"><span>${reportMeta}</span><span>Score ${escapeHtml(String(paper.relevance_score ?? ""))}</span></div>
        <p class="paper-card-preview">${escapeHtml(previewText(ai.tldr || paper.summary || "", 170))}</p>
        <p class="paper-card-help">${escapeHtml(previewText(ai.help_to_user || ai.idea_spark?.idea || "点击查看详情，阅读完整中文简介与 PDF。", 110))}</p>
        <div class="paper-card-footer"><div class="paper-card-categories">${escapeHtml((paper.categories || []).join(", "))}</div><button type="button" class="btn details-btn" data-paper-id="${normalizePaperId(paper.id)}">Details</button></div>
      </article>
    `;
  };

  const bindListEvents = () => {
    document.querySelectorAll(".paper-card").forEach((card) => card.addEventListener("click", (event) => !event.target.closest("a, button") && paperDetailController?.openById(decodeURIComponent(card.dataset.paperId || ""))));
    document.querySelectorAll(".details-btn").forEach((button) => button.addEventListener("click", (event) => (event.stopPropagation(), paperDetailController?.openById(decodeURIComponent(button.dataset.paperId || "")))));
  };

  const renderPaperList = (papers) => {
    const container = document.getElementById("papers");
    container.innerHTML = papers.length ? papers.map(paperCard).join("") : '<div class="empty-state panel">No papers match the current filters.</div>';
    if (papers.length) bindListEvents();
    paperDetailController?.refresh();
  };

  const renderDomainChips = () => {
    const container = document.getElementById("domain-filter-chips");
    const select = document.getElementById("domain-filter");
    if (!container || !select) return;
    syncDomainOptions();
    const counts = currentPapers.reduce((acc, paper) => ((acc[paper.domain || "general"] = (acc[paper.domain || "general"] || 0) + 1), (acc.all += 1), acc), { all: 0 });
    container.innerHTML = Array.from(select.options)
      .map((option) => ({ value: option.value, label: getDomainLabel(option.value), count: counts[option.value] || (option.value === "all" ? counts.all : 0) }))
      .map((item) => `<button type="button" class="filter-chip${item.value === select.value ? " active" : ""}" data-domain="${escapeHtml(item.value)}"><span class="filter-chip-label">${escapeHtml(item.label)}</span><span class="filter-chip-count">${escapeHtml(String(item.count || 0))}</span></button>`)
      .join("");
    container.querySelectorAll(".filter-chip").forEach((button) => button.addEventListener("click", () => ((select.value = button.dataset.domain || "all"), applyDomainFilter())));
  };

  const applyDomainFilter = () => {
    const selected = document.getElementById("domain-filter").value;
    currentFilteredPapers = selected === "all" ? currentPapers : currentPapers.filter((paper) => (paper.domain || "general") === selected);
    renderDomainChips();
    renderPaperList(currentFilteredPapers);
  };

  const loadScope = async (scope) => {
    const scopeDates = getScopeDates(availableDates, scope);
    if (!scopeDates.length) throw new Error("No daily reports found in the selected range.");
    currentPapers = aggregateDailyPayloads(await Promise.all(scopeDates.map((date) => fetchDataJson(`daily/${date}.json`))));
    currentDateMode = scope.mode;
    currentDate = scope.mode === "single" ? scope.date : scopeDates[0];
    currentDateRange = scope.mode === "range" ? { start: scopeDates[scopeDates.length - 1], end: scopeDates[0], dates: scopeDates } : null;
    currentDateLabel = buildDateScopeLabel(scope.mode === "single" ? scope : { mode: "range", start: currentDateRange.start, end: currentDateRange.end });
    document.getElementById("date-select").value = scopeDates[0];
    updateDateTrigger(scope.mode === "single" ? scope : { mode: "range", start: currentDateRange.start, end: currentDateRange.end });
    document.getElementById("meta").innerHTML = `<span class="meta-pill meta-pill-strong">${escapeHtml(currentDateLabel)}</span><span class="meta-pill">${escapeHtml(String(currentPapers.length || 0))} papers</span><span class="meta-pill">${currentDateMode === "range" ? `${scopeDates.length}-day range` : "Single day"}</span>`;
    renderStatus();
    applyDomainFilter();
  };

  const main = async () => {
    applyTheme(getTheme(), false);
    const index = await resolveDataBasePath();
    availableDates = [...(index.dates || [])];
    document.getElementById("title").textContent = index.title || "ArXiv Research Assistant";
    const select = document.getElementById("date-select");
    availableDates.forEach((date) => select.appendChild(Object.assign(document.createElement("option"), { value: date, textContent: date })));
    const initial = index.latest || availableDates[0];
    if (!initial) return void (document.getElementById("meta").textContent = "No data yet. Run the pipeline first.");
    await loadScope({ mode: "single", date: initial });
    paperDetailController = detail.createController({ getPapers: () => currentFilteredPapers, getScopeLabel: () => currentDateLabel || currentDate, getScopeCacheKey: getCurrentScopeCacheKey, onStateChange: renderStatus }).init();
    [document.getElementById("theme-dialog"), document.getElementById("date-dialog")].forEach(enableDialogOutsideClose);
    renderStatus();
    syncDateSelectionDialog();
    document.getElementById("domain-filter").addEventListener("change", applyDomainFilter);
    document.getElementById("open-date-picker").addEventListener("click", () => {
      const dialog = document.getElementById("date-dialog");
      syncDateSelectionDialog();
      if (!dialog.open) dialog.showModal();
    });
    document.querySelectorAll(".mode-toggle-btn").forEach((button) => button.addEventListener("click", () => syncDateSelectionDialog({ ...readScopeFromDialog(availableDates), mode: button.dataset.mode || "single" })));
    document.querySelectorAll(".date-quick-btn").forEach((button) => button.addEventListener("click", () => {
      const scope = buildRangeScopeFromCount(availableDates, button.dataset.range || "latest");
      if (scope) syncDateSelectionDialog(scope);
    }));
    document.getElementById("apply-date-selection").addEventListener("click", async () => {
      const button = document.getElementById("apply-date-selection");
      button.disabled = true;
      button.textContent = "Loading...";
      try {
        const scope = readScopeFromDialog(availableDates);
        await loadScope(scope.mode === "range" ? scope : { mode: "single", date: clampDateToAvailable(availableDates, scope.date) });
        document.getElementById("date-dialog").close();
      } catch (error) {
        window.alert(error.message || "Failed to load the selected range.");
      } finally {
        button.disabled = false;
        button.textContent = "Apply";
        syncDateSelectionDialog();
      }
    });
    document.getElementById("open-theme-picker").addEventListener("click", () => {
      const dialog = document.getElementById("theme-dialog");
      updateThemeSelectionUI();
      if (!dialog.open) dialog.showModal();
    });
    document.getElementById("open-settings").addEventListener("click", () => paperDetailController?.showSettings());
    document.querySelectorAll(".theme-option").forEach((option) => option.addEventListener("click", () => (applyTheme(option.dataset.theme || DEFAULT_THEME), renderStatus())));
    document.getElementById("reset-theme").addEventListener("click", () => (applyTheme(DEFAULT_THEME), renderStatus()));
  };

  main().catch((error) => {
    document.getElementById("meta").textContent = `Load failed: ${escapeHtml(error.message || "unknown error")}`;
  });
})();
